// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTEJqnuSFFkyCDzqVI1RHgDZEmgBNPaxE',
    appId: '1:838589388321:web:aa734e5d0c89b6fe24b560',
    messagingSenderId: '838589388321',
    projectId: 'appyto',
    authDomain: 'appyto.firebaseapp.com',
    storageBucket: 'appyto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJanLvZKAhoj-HCAA02EA-PoDZtdUjR6w',
    appId: '1:838589388321:android:57fb04c99090674d24b560',
    messagingSenderId: '838589388321',
    projectId: 'appyto',
    storageBucket: 'appyto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYn8vFuTxZm81Ug_LqbZzIdL60ggOJ8xA',
    appId: '1:838589388321:ios:7b62be00f957639524b560',
    messagingSenderId: '838589388321',
    projectId: 'appyto',
    storageBucket: 'appyto.appspot.com',
    iosBundleId: 'com.eno.appy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYn8vFuTxZm81Ug_LqbZzIdL60ggOJ8xA',
    appId: '1:838589388321:ios:44b015d71bbca79424b560',
    messagingSenderId: '838589388321',
    projectId: 'appyto',
    storageBucket: 'appyto.appspot.com',
    iosBundleId: 'com.eno.appy.RunnerTests',
  );
}
